### ISSUE TITLE
Flipped controllers on Rift S and Quest 2 (Virtual Desktop)

### ISSUE THREAD

**Issue by CrimsonZA** [TrackLab/ViRe#1]
the orientation for Rift S and Quest 2 controllers aren't lining up correctly and you have to reposition the controllers to make the hands of the character sensible which can be awkward.

**Comment by B4rtux** [comment]
how we can reflip ?

**Comment by DarastrixJames** [comment]
This issue still persists.  The controllers are completely backwards and recalibration is a nightmare.  It's been nearly sixth months since this has been reported with no fix.  What's the deal?

**Comment by SarenDev** [comment]
Unfortunately, we currently don’t have the resources to test with other headsets and controllers, which is why we haven’t responded to this issue.

We are planning to look into adding a way for users to calibrate their controller manually inside ViRe

**Comment by SarenDev** [comment]
Oculus controllers are now oriented correctly and have valid bindings. This fix will be a part of an upcoming update

**Comment by SarenDev** [comment]
Fixed in V0.11.1A
