### ISSUE TITLE
File manager can't be interacted with on Windows 10&11

### ISSUE THREAD

**Issue by SarenDev** [TrackLab/ViRe#2]
The file manager used for selecting directories and audio files can't be interacted (i.e., clicked on) with on Windows 11.
This only affects the compiled version; it still works in the editor.

Updating to Unity 2021.3.9f1 as per [this suggestion](https://github.com/yasirkula/UnitySimpleFileBrowser/issues/70) did not resolve the issue

**Comment by SarenDev** [comment]
A Discord user confirmed the issue on their machine but for Windows 10. They also claim the problem goes away after waiting a bit.

**Comment by SarenDev** [comment]
This issue _probably_ isn't caused by Unity's New Input system because [this suggestion](https://github.com/yasirkula/UnitySimpleFileBrowser#new-input-system-support) is already implemented and tested. Switching to the Legacy Input system doesn't solve the issue.

The "drone" camera (controlled from the PC) isn't the cause either, since disabling it doesn't affect the problem.

**Comment by SarenDev** [comment]
This appears to be fixed in newer versions of Windows 10 & 11. I don't know how, but the issue is gone from the previous ViRe versions.

**Comment by RiddleMajor** [comment]
No, this issue is still very present and makes me completely unable to use the software since it's not saving anywhere

**Comment by SarenDev** [comment]
Can you try the test build at <https://github.com/TrackLab/ViRe/releases/tag/v0.12.1A> to see if the plugin version bump fixed the issue, @RiddleMajor?

**Comment by SarenDev** [comment]
In my testing, the issue was resolved with the test build changes. Please let me know if it persists
